### ISSUE TITLE
CTD randomly 

### ISSUE THREAD

**Issue by MA7596** [The-Grand-Combination/The-Grand-Combo#105]
The game crashes randomly after a period of time running. It seems to crash at the beginning of the next in game month no matter what speed im running. I tried running on the current Vic 2 version as well as the beta 3.04 version on steam. Ive had this problem on the Dev build and master branch versions.

**Comment by christofergartner** [comment]
Are you on the Discord? You will probably get help faster there.

**Comment by MA7596** [comment]
What would be the discord address?
