### ISSUE TITLE
The Reichswehr Decision for the German Confederation grants cash instead of subtracting it

### ISSUE THREAD

**Issue by Danarca** [The-Grand-Combination/The-Grand-Combo#116]
I formed the German Confederation through the Crown in the Gutter event, and finally got to the point where I could reform the Reichswehr, but instead of subtracting 3mil from me, I gained 1.3m (and some change).

**Comment by Kspeher-Victoria2** [comment]
Thank you for the information, a fix has be published by me. Please download the new dev build or if updating to a new dev build won't work (due save game crashes) use the .txt file below and place it into TGC/decisions and when prompted
 replace the file. Please comment back on this post to tell me if it worked for you, as to know if I can close this issue. :)
[GEF.txt](https://github.com/rderekp/The-Grand-Combo/files/6425923/GEF.txt)

Note: New Balance changes have been added (cash amounts)

Reform State 1.8mil->3mil
Reform State+Austria 1mil->1.5mil
Reform Army 3mil->2mil
Limit Austrian influence in army stayed the same.

Have a great day

**Comment by Danarca** [comment]
I reloaded an old save from 1859, and in 1860 pressed the Reichswehr decision with some 2m in cash, reduced me to 88k :)

So yeah, seems like your solution worked!
