### ISSUE TITLE
German confederation 1848 issues

### ISSUE THREAD

**Issue by Lopatouovalil** [The-Grand-Combination/The-Grand-Combo#127]
when you form GCF in 1848 you get 2 additional modifiers/penalties when you inherit Austria. their tooltips are saying that you can remove them with cash in 1860, but in reality it is 1870 or 1880. 
About outraged Europe, i think you should decrease its length. to the year 1990 is too long.
event 999362 will still be triggered even after 999363 happened.

**Comment by Kspeher-Victoria2** [comment]
Hello, thank you for bringing it to my attention. It appears the localization is outdated then, the time length remove the modifiers has been increased in previous updates. This was done to debuff Germany more. Outraged Europe time was also increased, for the same reason. If you would like to change it you can go under "GEF Events" in the mod folder. Simply search for "outraged-europe" to adjust the time on it. On the last one, it appears that I forgot to include a line to remove the country flag. 

For a adjusted file, drag and drop it into the events folder in the TGC mod folder. Replace when asked.

Thank you
[GEF Events.txt](https://github.com/rderekp/The-Grand-Combo/files/6883245/GEF.Events.txt)
