### ISSUE TITLE
treaty with netherlands.

### ISSUE THREAD

**Issue by Lopatouovalil** [The-Grand-Combination/The-Grand-Combo#128]
treaty where you conquer Netherlands  don't take province 3384, so it blocks event chain and decisions for it.

**Comment by Kspeher-Victoria2** [comment]
Fixed, hopefully, thank you for bringing it to my attention. You can download the new dev build or drag and drop this file into the TGC mod folder under decisions. Replace when asked. Thank you, again.
[GEF.txt](https://github.com/rderekp/The-Grand-Combo/files/6883274/GEF.txt)
