### ISSUE TITLE
Hard crash to desktop after Heavenly Kingdom breaks apart into the Warlord Era

### ISSUE THREAD

**Issue by Ruskie-Business** [The-Grand-Combination/The-Grand-Combo#129]
Playing an Italy playthrough and during my game, the Taiping Rebellion was won by the Heavenly Kingdom.

Later on, around 1903 to 1904, when China breaks apart into the Warlord Era, the game hard crashes to desktop. Sometimes I might get lucky where the game may still continue on for a few more months until it crashes from different autosaves.

**Comment by ColdSlav** [comment]
Is this issue still present?

**Comment by ColdSlav** [comment]
I assume this issue has been solved.
