### ISSUE TITLE
Negative days to justify war as Tokugawa Japan

### ISSUE THREAD

**Issue by DingPum** [The-Grand-Combination/The-Grand-Combo#149]
There seems to be a bug for early game Tokugawa Shogunate, it says it will take a negative amount of days to justify. So when you actually try to justify, no progress will ever be made and you are just stuck. My guess is that it might have to do with the negative modifiers to casus belli acquisition it gets with Sakoku and Isolationism, and they are for some reason making it seemingly impossible to declare war in the early game as Tokugawa

![20211002044101_1](https://user-images.githubusercontent.com/62076931/135711187-797b23d8-deff-4ad6-82ec-e90cf2ce76ee.jpg)

**Comment by GeneralVonGelre** [comment]
This goes for all isolationist uncivs and is intentional.
