### ISSUE TITLE
brasil adquiere el río yurua automáticamente 

### ISSUE THREAD

**Issue by juniorsaa21** [The-Grand-Combination/The-Grand-Combo#150]
brasil adquiere el río yurua automáticamente cuando juego con peru sin haber perdido guerra ni nada ,ademas hay una decisión que por mas que la acepto me aparece otra vez (es la decisión de la parte de la región de la amazonia entre peru y brasil),siempre me da mas 10 de infamia infinitamente.

**Comment by anzu-3278** [comment]
English please. Can you post a screenshot of the decision in the discord so we know what you have an issue with.

**Comment by juniorsaa21** [comment]
Brazil acquires the yurua river automatically when I play with Peru without having lost war or anything, also there is a decision that even though I accept appears to me again (it is the decision of the part of the Amazon region between Peru and Brazil), It always gives me more than 10 infamy infinitely.
