### ISSUE TITLE
I'm stuck in a war that I have won

### ISSUE THREAD

**Issue by vlf4230** [The-Grand-Combination/The-Grand-Combo#155]
Hi,

I am playing TGC as the USA.  I was aiding France as an ally in Europe when I received a message that somehow war had both started and ended in the states between the me ( USA ) and the Confederate States of America.  When I refocused the map on the USA I found that Kentucky had ceded from the USA, but a moment later I was given the option to take it back as a Core.  I did and the map was back the way it when I left to help France.

I noticed a little while later that it had that I was still at war.  When I look at current wars it shows that I have completely won the war with CSA at 100%.  I cannot select the CSA to offer any type of Peace.  I have tried locating it on the Map, but I'm guessing that once I took Kentucky back as a Core that wiped that out.

It's now 10+ years later and I've restarted the gave a couple of times, but with no luck.  I looked up the knows bugs but this is not on the list.  Lucky me.  

Any suggestions?  The only reason I'm not plowing forward is the numerous decisions open to the USA that require it to be at peace.

Thanks!

Jim

**Comment by GeneralVonGelre** [comment]
This has been fixed (a little while ago)
