### ISSUE TITLE
Hard crash because of Italy going communist from rebels, specifically the 'Communist Movement finds a country to stand behind' event and others

### ISSUE THREAD

**Issue by eagles980** [The-Grand-Combination/The-Grand-Combo#162]
Italy flipped communist because of rebels during a massive European war they're participating in. If I do nothing and let time progress the event pops up. Simply mousing over one of the two event choices crashes the game. If I tag into Italy and pick the 'Choose our course' decision, and THEN tag back into Serbia the event works seemingly normally and I get a CB on them to remove their communist government. However, the event pops up a SECOND time eventually (month or two?) and the game crashes anyway. So, I tried tagging back to Italy the second time the event pops up clicked it away (no crash) and got THEIR 'The revolution subverted' (paraphrasing) which happened after a separate event where their dictator gets assasinated (related event? Coincidence?) which promptly crashed the second I moused over it. 

This save might be borked. I'd love to link the file but I have no idea where to find it. Tried looking in the same place the HPM equivalent would be found too. (GCM folder in documents)

Update: the save is NOT borked. I just had to tag to a completely unrelated country (Persia) and let the AI deal with all the broken events for the better part of a year. No crashes! Positives? I can continue my game as normal. Negatives? The AI ran my country for a year...

**Comment by ColdSlav** [comment]
Same for this one, does it still happen?
