### ISSUE TITLE
Hard crash because of the Russia 'free the Balkans' event and subsequent war

### ISSUE THREAD

**Issue by eagles980** [The-Grand-Combination/The-Grand-Combo#163]
First the Balkan situation. ALL the Balkan countries had their cores freed and are independent OR exist as a released vassal by the Ottomans themselves (Albania). I as an independent and UNSPHERED Serbia get an event from Russia to join them in a war to free the Balkans. Only problem? As I just said the Balkans are already free with the exception of Albania, however I'm left with *no choice* but to join them AND I get sphered the second the decision is clicked greatly damaging my economy that as a minimally indusrialized, aspiring colonial nation depends heavily on tariffs. This part is not so much a bug but what I feel is an awkwardly designed railroaded event that WOULD be good for me as Serbia in most other circumstances but actually punished me horribly for actually doing well before it kicks off. I would love for it to be reworked to at least include a decision to stay out completely as an uninterested observer or even something cute like instead choosing to fight on the Ottoman side to maintain the status quo and prevent Russia from getting more influence in the region. 

The actual bug is what happens a short time after the war begins (or even before this. Tested multiple times.) The game  eventually crashes every time. Worked around the crash by tagging into another country at or around the time the event appears as well as giving back a few provinces from each free Balkan country to the Turks through console so there's actually something for the war to "free." Don't remember if I tagged into Russia as well and messed around there but I might have. In any case, with my console interventions the war concluded as one would expect (territorial gains for countries like Bulgaria, Russia taking Constantinople, so on) with no further issues from the event. 

Similar to the other issue I posted, I have no idea where to find the save or I'd link it as well.

**Comment by ColdSlav** [comment]
Is this issue still present?
