### ISSUE TITLE
Game breaking bug as Imperial Japan in regards to the 'Colonial Tech Inheritence' event

### ISSUE THREAD

**Issue by eagles980** [The-Grand-Combination/The-Grand-Combo#171]
Mere days after starting the game the pop up appears which is all well and good despite the fact that approximately five duplicate windows of it appear and have to be clicked away individually. However, the major problem lies in the fact that they pop up AGAIN and again and again every few days seemingly ad infinitum pausing the game each time, requiring that they be clicked away until time can progress as usual. I would try testing the 'tag out, wait for awhile, and tag back in' strategy that's worked to somewhat circumvent the other bugs but I can't find the Imperial Japan country tag name anywhere.

**Comment by ColdSlav** [comment]
Does this issue still occur?
