### ISSUE TITLE
Why do I lose Suez territory and cores after finishing building it?

### ISSUE THREAD

**Issue by rybandrei2014** [The-Grand-Combination/The-Grand-Combo#326]
I am playing as Switzerland and decided to influence Egypt in order to build Suez and get access to Africa colonization. Unfortunately, after I finished building it I somehow lost Suez province and all my cores, is it expected behavior? Will the same happen in Panama and Nicaragua?

**Comment by joelAVS** [comment]
Suez was, sovereign-wise, actually owned by Egypt, even if the canal itself was half operated by foreign companies. So you don't keep the land.

The situation in Panama was a tad different, the US pretty much had full control of the land around the canal. So, in game, you get to keep the canal. I believe the same goes for Nicaragua.

**Comment by rybandrei2014** [comment]
Oh I see, thanks for clarifying. It makes sense from historical viewpoint and I appreciate that, but I think historical accuracy makes building the canal in TGC useless, as it doesn't provide the nation who builds it any worthy benefits (besides losing bunch of money for some prestige points and possibility to travel through canal). Also investing more money for speeding up the building process is also useless, as I will lose this province anyway and faster for my money...
