### ISSUE TITLE
Broken Decisions

### ISSUE THREAD

**Issue by CipKac** [The-Grand-Combination/The-Grand-Combo#92]
NOT_title
allow_title

AI spams these in the current version. I might have got these names wrong.

(By which I mean the latest updated dev build)

**Comment by LouisTheFly** [comment]
Hi, how are you noticing the AI take these? In the event notifications on the bottom right? Atm I cant see this problem happening on the current version.

**Comment by CipKac** [comment]
Yes. It's on the notifications on the bottom right and in the decision screen the decisions have no effect or requirement. They spam the decisions and I've noticed they don't take any other because of this, which ends up breaking the game.

I'll try a clean reinstall of the developer build and come back to you again tho that might take a while since my internet is acting up lately

**Comment by CipKac** [comment]
I've reinstalled the mod cleanly and the decisions are gone. I think I might have downloaded the Master branch by accident instead of the Developer Build, otherwise maybe it was fixed? I don't know, but it's solved.
