### ISSUE TITLE
Suggestion: British reconquest in North America

### ISSUE THREAD

**Issue by CipKac** [The-Grand-Combination/The-Grand-Combo#94]
I've always found a bit odd that the french get to conquer Canada and a ton of american land and/or go full napoleonic in europe after the concert was put in place but the british never get a chance to go ahistorically wacky. I guess there's less of an issue with yankees rebelling on part of the french, but I would find interesting if there was a way to go bonkers and say, hold on to the Kingdom of Hannover or conquer the americans again.

EDIT: Sorry for double posting lul I didn't think the first one would be sent when my internet started acting up.

**Comment by LouisTheFly** [comment]
It is possible for the british to sieze new england and some midwest territiories if they successfully defeat the US crusade for canada, but the main reason for lack of ahistorical stuff is that they have so much historical stuff that its probably way down on the priority list. The hannover thing is a maybe tho

**Comment by CipKac** [comment]
Yeah, I recall it was in More Stuff HFM. Though the player is forced to release New England and it quickly becomes a great power which imo is a bit lame compared to, say, conquering 1836ish USA minus Louisiana and interacting with yankees, dixie and the slavery issue. Though I guess that's wishful thinking on my part as it would take a lot of work to do something like that lol

It's also I think a bit weird to see domionish New England using the cross of saint george as opposed to a union jack on their flag.

Maybe I should open a separate issue on the case of puppets becoming industrialized great powers.

**Comment by emprahtheodosius** [comment]
> Yeah, I recall it was in More Stuff HFM. Though the player is forced to release New England and it quickly becomes a great power which imo is a bit lame compared to, say, conquering 1836ish USA minus Louisiana and interacting with yankees, dixie and the slavery issue. Though I guess that's wishful thinking on my part as it would take a lot of work to do something like that lol
> 
> It's also I think a bit weird to see domionish New England using the cross of saint george as opposed to a union jack on their flag.
> 
> Maybe I should open a separate issue on the case of puppets becoming industrialized great powers.

This unfortunately cannot be fixed unless you manually reduce numbers of great power spots in the world. I personally play the game with 6. All you need to do is change this particular defines.csv line:

> GREAT_NATIONS_COUNT = 8,

That aside, some whack, player-only, infamy ridden path may be possible for reclaiming the 13 colonies as Britain. Its currently low on the priority list, though.
