### ISSUE TITLE
Unable to form Gran Columbia any earlier then 1890

### ISSUE THREAD

**Issue by DingPum** [The-Grand-Combination/The-Grand-Combo#95]
Not sure if this was intended, but the form Gran Columbia decision will not work until you get The Dark Continent due to required Columbian cores lying in the Amazon. To me it seems kind of silly that you wouldn't be able to form Gran Columbia just because you didn't own low pop/low life rating jungle provinces in the Amazon.

**Comment by christofergartner** [comment]
Does Colombia not have events to colonise that land?

**Comment by GeneralVonGelre** [comment]
On more up to date branches this is resolved using events that gradually give the uncolonised land to their respective owners.

Closing this for now.
